# Here you can configure what items are allowed to be created by different players.
# There can be multiple permission groups, the default group must exist. If there
# are more groups, the one with the highest priotiry where the player has the required
# permission ist used. the permission to use items of a group is 
# creativeitemcontrol.group.[.groupname], for example creativeitemcontrol.group.builder
# 
# forbidden items are not allowed to be spawned with any components, otherwise the components
# are checked, for details about components hava a look at the minecraft wiki:
# https://minecraft.wiki/w/Data_component_format
#
# If an item is blocked, the player gets the message configured in messages.unavailable.
# $itemtype$ can be used for the item type in the message.
debug: false
messages:
  unavailable: 'This item is not available!'
  tooLarge: 'This item is blocked, because it contained too much data!'
groups:
  default:
    max_item_size_bytes: 50000
    forbidden_items:
      - command_block
      - chain_command_block
      - repeating_command_block
      - command_block_minecart
      - jigsaw
      - structure_block
      - structure_void
      - barrier
      - debug_stick
      - light
    allow_all_components: false
    components:
      attack_range:
        allow: false
      attribute_modifiers:
        allow_all: false
        allow: []
        allow_modify_display: false
        display_max_custom_name_length: 0
      banner_patterns:
        max_patterns: 6
      bees:
        max_bees: 0
        allow_entity_data: false
        allow_all_entities: false
      block_entity_data:
        allow: false
      block_state:
        allow: true
      blocks_attacks:
        allow: false
      break_sound:
        allow: false
      bucket_entity_data:
        allow: true
      can_break:
        allow: false
      can_place_on:
        allow: false
      consumable:
        allow: false
        allow_sounds: false
        allow_effects: false
        allow_teleport: false
      container_loot:
        allow: false
      custom_data:
        allow_all: false
        allowed_keys: []
      custom_model_data:
        allow: false
      custom_name:
        allow: true
        allow_formating: false
        max_length: 40
      damage_resistant:
        allow: false
      damage_type:
        allow: false
      death_protection:
        allow: false
        allow_sounds: false
        allow_effects: false
        allow_teleport: false
      enchantable:
        allow: false
      enchantment_glint_override:
        allow: false
      enchantments:
        allow_on_all_items: false
        override_max_level: {}
      entity_data:
        allow: false
        allowPaintings: true
        allowItemFrames: false
        allowItemsInItemFrames: false
        allowArmorStands: false
        allowItemsInArmorStands: false
      equippable:
        allow: false
      firework_explosion:
        allow: true
      fireworks:
        allow: true
        max_exposions: 8
        max_flight_time: 3
      food:
        allow: false
      glider:
        allow: false
      instrument:
        allow_custom: false
      item_name:
        allow: false
        allow_formating: true
        max_length: 4000
      item_model:
        allow: false
      kinetic_weapon:
        allow: false
      lock:
        allow: false
      lodestone_tracker:
        allow: false
      lore:
        allow: false
        allow_formating: false
        max_lines: 40
        max_length: 4000
      map_decorations:
        allow: false
        max_decorations: 50
      map_id:
        allow: false
      max_damage:
        allow: false
      max_stack_size:
        allow: false
      minimum_attack_charge:
        allow: false
      note_block_sound:
        allow: false
      ominous_bottle_amplifier:
        allow: true
      piercing_weapon:
        allow: false
      pot_decorations:
        allow: true
      potion_contents:
        allow: true
        custom_color: false
        custom_effects: false
        custom_name: false
        custom_name_allow_formating: false
        custom_name_max_length: 4000
      potion_duration_scale:
        allow: false
      profile:
        allow: false
        allowLocalTextureOverride: false
      provides_banner_patterns:
        allow: false
      provides_trim_material:
        allow: false
      rarity:
        allow: false
      recipes:
        allow: false
      repair_cost:
        allow: false
      repairable:
        allow: false
      stored_enchantments:
        allow_on_all_items: false
        override_max_level: {}
      suspicious_stew_effects:
        allow: true
        max_duration: 160
      swing_animation:
        allow: false
      tool:
        allow: false
      tooltip_display:
        allow: false
      tooltip_style:
        allow: false
      trim:
        allow: false
      unbreakable:
        allow: false
      use_cooldown:
        allow: false
      use_effects:
        allow: false
      use_remainder:
        allow: false
      variants:
        allow: true
      weapon:
        allow: false
      writable_book_content:
        allow: false
      written_book_content:
        allow: false
  builder:
    priority: 10
    max_item_size_bytes: 50000
    forbidden_items:
      - command_block
      - chain_command_block
      - repeating_command_block
      - command_block_minecart
      - jigsaw
      - structure_block
    allow_all_components: false
    components:
      attack_range:
        allow: true
      attribute_modifiers:
        allow_all: false
        allow:
          - movement_speed
        allow_modify_display: true
        display_max_custom_name_length: 1000
      banner_patterns:
        max_patterns: 16
      bees:
        max_bees: 3
        allow_entity_data: false
        allow_all_entities: false
      block_entity_data:
        allow: false
      block_state:
        allow: true
      blocks_attacks:
        allow: true
      break_sound:
        allow: true
      bucket_entity_data:
        allow: true
      can_break:
        allow: true
      can_place_on:
        allow: true
      consumable:
        allow: true
        allow_sounds: true
        allow_effects: true
        allow_teleport: true
      container_loot:
        allow: true
      custom_data:
        allow_all: false
        allowed_keys: []
      custom_model_data:
        allow: true
      custom_name:
        allow: true
        allow_formating: true
        max_length: 4000
      damage_resistant:
        allow: true
      damage_type:
        allow: true
      death_protection:
        allow: true
        allow_sounds: true
        allow_effects: true
        allow_teleport: true
      enchantable:
        allow: true
      enchantment_glint_override:
        allow: true
      enchantments:
        allow_on_all_items: true
        override_max_level:
          protection: 4
      entity_data:
        allow: false
        allowPaintings: true
      equippable:
        allow: true
      firework_explosion:
        allow: true
      fireworks:
        allow: true
        max_exposions: 256
        max_flight_time: 127
      food:
        allow: true
      glider:
        allow: true
      instrument:
        allow_custom: false
      item_name:
        allow: true
        allow_formating: true
        max_length: 4000
      item_model:
        allow: true
      kinetic_weapon:
        allow: true
      lock:
        allow: true
      lodestone_tracker:
        allow: true
      lore:
        allow: true
        allow_formating: true
        max_lines: 40
        max_length: 4000
      map_decorations:
        allow: true
        max_decorations: 50
      map_id:
        allow: true
      max_damage:
        allow: true
      max_stack_size:
        allow: true
      minimum_attack_charge:
        allow: true
      note_block_sound:
        allow: true
      ominous_bottle_amplifier:
        allow: true
      piercing_weapon:
        allow: true
      pot_decorations:
        allow: true
      potion_contents:
        allow: true
        custom_color: true
        custom_effects: true
        custom_name: true
        custom_name_allow_formating: true
        custom_name_max_length: 4000
      potion_duration_scale:
        allow: true
      profile:
        allow: true
        allowLocalTextureOverride: true
      provides_banner_patterns:
        allow: true
      provides_trim_material:
        allow: true
      rarity:
        allow: true
      recipes:
        allow: true
      repair_cost:
        allow: true
      repairable:
        allow: true
      stored_enchantments:
        allow_on_all_items: true
        override_max_level:
          protection: 4
      suspicious_stew_effects:
        allow: true
        max_duration: 160
      swing_animation:
        allow: true
      tool:
        allow: true
      tooltip_display:
        allow: true
      tooltip_style:
        allow: true
      trim:
        allow: true
      unbreakable:
        allow: true
      use_cooldown:
        allow: true
      use_effects:
        allow: true
      use_remainder:
        allow: true
      variants:
        allow: true
      weapon:
        allow: true
      writable_book_content:
        allow: true
      written_book_content:
        allow: true
  admin:
    priority: 20
    max_item_size_bytes: -1
    forbidden_items: []
    allow_all_components: true
    components:
      attack_range:
        allow: true
      attribute_modifiers:
        allow_all: true
        allow:
          - movement_speed
        allow_modify_display: true
        display_max_custom_name_length: 4000
      banner_patterns:
        max_patterns: 16
      bees:
        max_bees: 3
        allow_entity_data: false
        allow_all_entities: false
      block_entity_data:
        allow: false
      block_state:
        allow: true
      blocks_attacks:
        allow: true
      break_sound:
        allow: true
      bucket_entity_data:
        allow: true
      can_break:
        allow: true
      can_place_on:
        allow: true
      consumable:
        allow: true
        allow_sounds: true
        allow_effects: true
        allow_teleport: true
      container_loot:
        allow: true
      custom_data:
        allow_all: false
        allowed_keys: []
      custom_model_data:
        allow: true
      custom_name:
        allow: true
        allow_formating: true
        max_length: 4000
      damage_resistant:
        allow: true
      damage_type:
        allow: true
      death_protection:
        allow: true
        allow_sounds: true
        allow_effects: true
        allow_teleport: true
      enchantable:
        allow: true
      enchantment_glint_override:
        allow: true
      enchantments:
        allow_on_all_items: true
        override_max_level:
          protection: 4
      entity_data:
        allow: true
        allowPaintings: true
      equippable:
        allow: true
      firework_explosion:
        allow: true
      fireworks:
        allow: true
        max_exposions: 256
        max_flight_time: 127
      food:
        allow: true
      glider:
        allow: true
      instrument:
        allow_custom: false
      item_model:
        allow: true
      item_name:
        allow: true
        allow_formating: true
        max_length: 4000
      kinetic_weapon:
        allow: true
      lock:
        allow: true
      lodestone_tracker:
        allow: true
      lore:
        allow: true
        allow_formating: true
        max_lines: 40
        max_length: 4000
      map_decorations:
        allow: true
        max_decorations: 50
      map_id:
        allow: true
      max_damage:
        allow: true
      max_stack_size:
        allow: true
      minimum_attack_charge:
        allow: true
      note_block_sound:
        allow: true
      ominous_bottle_amplifier:
        allow: true
      piercing_weapon:
        allow: true
      pot_decorations:
        allow: true
      potion_contents:
        allow: true
        custom_color: true
        custom_effects: true
        custom_name: true
        custom_name_allow_formating: true
        custom_name_max_length: 4000
      potion_duration_scale:
        allow: true
      profile:
        allow: true
        allowLocalTextureOverride: true
      provides_banner_patterns:
        allow: true
      provides_trim_material:
        allow: true
      rarity:
        allow: true
      recipes:
        allow: true
      repair_cost:
        allow: true
      repairable:
        allow: true
      stored_enchantments:
        allow_on_all_items: true
        override_max_level:
          protection: 4
      suspicious_stew_effects:
        allow: true
        max_duration: 160
      swing_animation:
        allow: true
      tool:
        allow: true
      tooltip_display:
        allow: true
      tooltip_style:
        allow: true
      trim:
        allow: true
      unbreakable:
        allow: true
      use_cooldown:
        allow: true
      use_effects:
        allow: true
      use_remainder:
        allow: true
      variants:
        allow: true
      weapon:
        allow: true
      writable_book_content:
        allow: true
      written_book_content:
        allow: true